### ISSUE TITLE
ch9-schemas-and-documentation

### ISSUE THREAD

**Issue by izolotarev** [wsvincent/restapiswithdjango#2]
Looks like two authorization paths were accidentally removed from blog_project/urls.py. Because two endpoints were not available:
api/v1/rest-auth/
api/v1/rest-auth/registration/

These paths were absent:
path('api/v1/rest-auth/', include('rest_auth.urls')),
path('api/v1/rest-auth/registration/', include('rest_auth.registration.urls')),

**Comment by wsvincent** [comment]
Yes you are quite correct @izolotarev ! Fixing. In addition, DRF 3.10+ has new docs so I'm updating that as well :)
