### ISSUE TITLE
Ch5 'posts' APIreturns User.id instead of User.username

### ISSUE THREAD

**Issue by bluginbuhl** [wsvincent/restapiswithdjango#33]
The API endpoint `/api/v1/<int:pk>` returns the serialized `Post` object with `author` equal to the `User.id`, _i.e._,

```
{
    "id": 1,
    "author": 1,
    "title": "Test Post 1",
    "body": "This is the first post!",
    "created_at": "2020-09-22T22:30:03.173687Z"
}
```

It would be more useful to return `User.username` for `author`. This would simplify rendering the data on the frontend. For example:

```
{
    "id": 1,
    "author": "terrytesterson",
    "title": "Test Post 1",
    "body": "This is the first post!",
    "created_at": "2020-09-22T22:30:03.173687Z"
}
```

**Comment by wsvincent** [comment]
Hi, Yup you are correct. I've fixed this in the 4.0 update. The `User` model defaults to `id` so we need to use the [source field](https://www.django-rest-framework.org/api-guide/fields/#source) to change it to username.

In your `posts/serializers.py` file this does the trick:

from rest_framework import serializers
from .models import Post


class PostSerializer(serializers.ModelSerializer):
    author = serializers.ReadOnlyField(source="author.username")  # new

    class Meta:
        fields = (
            "id",
            "author",
            "title",
            "body",
            "created_at",
        )
        model = Post
